# -*- coding: utf-8 -*-
"""P636.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V2aL2HwziL8XPFj0TTv1xXPOzMfLA_Cm
"""

import numpy as np
import pandas as pd



proj=pd.read_csv("World_development_mesurement.csv")

proj.head()

proj.shape

proj.dtypes
#checking for datatypes of columns

proj.describe()

proj.isna().sum()

proj.columns.nunique()

proj['Business Tax Rate'].unique()
# here checking for why buziness rate showing object data type Similarly checking for other columns

proj['Health Exp/Capita'].unique()

proj['Tourism Inbound'].unique()

# Here we see here that these columns has numeric datatype
#but dtype is appearing as object due to presence of $,%,',' signs

# we will change dtypes of above columns
obj_columns=['GDP','Business Tax Rate','Health Exp/Capita','Tourism Inbound','Tourism Outbound']
for i in obj_columns:
  proj[i]=proj[i].astype(str).str.replace('$','',regex=False).str.replace(',','',regex=False).str.replace('%','',regex=False)
  proj[i]=pd.to_numeric(proj[i],errors='coerce')

proj.dtypes

#checking for duplicates
proj.duplicated().sum()

proj.dropna(subset=['Population Urban'], inplace=True)
# dropping null values of population urban as they were 26 only

proj.isna().sum()

coll=proj.columns

import matplotlib.pyplot as plt
import seaborn as sns

columns=proj.columns
plt.figure(figsize=(15,25))

for a, i in enumerate(coll):
    plt.subplot(9, 3, a + 1)
    sns.boxplot(y=proj[i])
    plt.title(i, fontsize=10)
    plt.ylabel('')
    plt.tick_params(axis='y', labelsize=8)

plt.suptitle('Boxplots for Outlier Detection in Columns')
plt.show()

col = ['CO2 Emissions',
'Days to Start Business',
'Business Tax Rate',
'Energy Usage',
'GDP',
'Health Exp % GDP',
'Health Exp/Capita',
'Infant Mortality Rate',
'Life Expectancy Female','Life Expectancy Male','Mobile Phone Usage','Population 15-64','Population 65+','Tourism Inbound','Tourism Outbound',
'Lending Interest','Hours to do Tax']
#columns having outliers



def count_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    upper_bound = Q3 + 1.5 * IQR
    lower_bound = Q1 - 1.5 * IQR

    outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)]
    return len(outliers)

print("Number of outliers per numerical column:")
for col in proj.select_dtypes(include=np.number).columns:
    num_outliers = count_outliers(proj, col)
    print(f"'{col}': {num_outliers}")

col = ['CO2 Emissions', 'Days to Start Business', 'Business Tax Rate', 'Energy Usage', 'GDP', 'Health Exp % GDP', 'Health Exp/Capita', 'Infant Mortality Rate', 'Life Expectancy Female','Life Expectancy Male','Mobile Phone Usage','Population 15-64','Population 65+','Tourism Inbound','Tourism Outbound', 'Lending Interest','Hours to do Tax']

for i in col:
    # Check if the column exists in the DataFrame and has null values
    if  proj[i].isnull().any():
        median_value = proj[i].median()
        proj[i].fillna(median_value, inplace=True)

numerical_cols = proj.select_dtypes(include=np.number).columns.tolist()
col1 = [c for c in numerical_cols if c not in col]
# including dtype numeric bcoz it also includes object column country
for i in col1:
# Checking if the column exists in the DataFrame and has null values
    if  proj[i].isnull().any():
        mean_value = proj[i].mean()
        proj[i].fillna(mean_value, inplace=True)
#columns with no  outliers

proj.isna().sum()

#again checking for outliers
plt.figure(figsize=(12,24))
for a, i in enumerate(columns):
    plt.subplot(9, 3, a + 1)
    sns.boxplot(y=proj[i])
    plt.title(i, fontsize=10)
    plt.ylabel('')
    plt.tick_params(axis='y', labelsize=8)

def outlier_capping(proj, column):
 Q1 = proj[column].quantile(0.25)
 Q3 = proj[column].quantile(0.75)
 IQR = Q3 - Q1
 UE = Q3 + 1.5 * IQR
 LE = Q1 - 1.5 * IQR
 proj[column] = proj[column].apply(lambda x: UE if x > UE else LE if x < LE else x)

# Apply outlier capping to all numerical columns in the DataFrame 'proj'
for i in proj.select_dtypes(include=['int', 'float']).columns:
    outlier_capping(proj, i)
#treatment for all outlier columns

#proj.boxplot()
#or
#again checking for outliers
plt.figure(figsize=(12,24))
for a, i in enumerate(columns):
    plt.subplot(9, 3, a + 1)
    sns.boxplot(y=proj[i])
    plt.title(i, fontsize=10)
    plt.ylabel('')
    plt.tick_params(axis='y', labelsize=8)

#Outliers have been treated

proj.select_dtypes(include=np.number).corr(method="pearson")

plt.figure(figsize=(20, 8))
sns.heatmap(proj.select_dtypes(include=np.number).corr(method="pearson"), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix Heatmap')
plt.show()

"""Based on insights from above heatmap let's do visual exploration on bivariate continuous columns"""

plt.scatter(proj['CO2 Emissions'],proj['Energy Usage'])
plt.xlabel('CO2 Emissions')
plt.ylabel('Energy Usage')
plt.show()
# here we obsserve that country where energy usage high CO2 emmission increasing

plt.scatter(proj['CO2 Emissions'],proj['GDP'])
# it appears there is a positive correlation, suggesting that countries with higher
#GDP tend to have higher CO2 Emissions.

proj['GDP'].plot(kind='hist')
#here we see that GDP mainly for countries 0-0.6 billion dollars and very few countries
#have gdp higher than that and few countries have GDP greater than 2 billion dollars

plt.scatter(proj['Days to Start Business'],proj['GDP'])
# here there is no proper pattern observed but correlation matrix gives -0.2 value as we see that very few nations
#that require more no. of days to start business has higer GDP mostly they lie 1 billion dollars

plt.scatter(proj['Health Exp % GDP'],proj['Population 65+'])
#Health Exp in % of GDP increases for older Population which is visible from high correlation coefficient (0.50)

plt.scatter(proj['Population Urban'],proj['Infant Mortality Rate'])

proj = proj.drop(['Number of Records', 'Ease of Business'], axis=1, errors='ignore')
# because ease of business has high no. of null value and number of records has only one unique value

target=proj[["Country"]]
features=proj.drop(columns=["Country"])

from sklearn.preprocessing import StandardScaler
std=StandardScaler()
df=pd.DataFrame(std.fit_transform(features),columns=features.columns)
df.head()



# As our dataset is large non hierarchial clustering is prefered

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

wcss = []
silhouette_scores = []
for i in range(2, 11):
    model = KMeans(n_clusters=i, init='k-means++' , random_state=42, n_init=10)
    model.fit(df)
    wcss.append(model.inertia_)

    silhouette_scores.append(silhouette_score(df,model.labels_))

# Plot the Elbow Method

plt.figure(figsize=(10, 6))
plt.plot(range(2, 11), wcss, marker='o', linestyle='--')
plt.title('Elbow Method For Optimal k')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('WCSS')
plt.grid(True)
plt.show()

#By plotting we can see the Silhouette_score raising and dropping according k_means values
plt.figure(figsize=(6,3))
plt.plot(range(2,11),silhouette_scores,marker='o',
         color='red')
plt.title('Silhouette_score VS K-means')
plt.ylabel('silhouette_score')
plt.xlabel('k-means')
plt.show()

best_k_value = silhouette_scores.index(max(silhouette_scores)) + 2 # Corrected to add 2 for the actual k value
best_score1 = max(silhouette_scores)
print("best_k_value :",best_k_value)
print("best_score:",best_score1)

# Choose an optimal number of clusters based on the elbow method
k = 3

kmeans = KMeans(n_clusters=k)
cluster_labels = kmeans.fit_predict(df)
print(kmeans.cluster_centers_)
print(kmeans.labels_)
print(kmeans.inertia_)

md=pd.Series(cluster_labels)
df['clust']=md

df['clust']=md
df.plot(kind='scatter',x='GDP',y='Health Exp/Capita',c='clust',colormap='coolwarm')

sns.scatterplot(x="Energy Usage", y="GDP", hue='clust', data=df, palette='coolwarm')

from sklearn.decomposition import PCA
pca=PCA()
pca_values=pca.fit_transform(df)
pca=PCA(n_components=2)

plt.figure(figsize=(7,7))
sns.scatterplot(x=pca_values[:,0],y=pca_values[:,1],hue=md,palette='Set1',s=60)
plt.show()

from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors
x=df.values
neigh=NearestNeighbors()
nbrs=neigh.fit(x)
distances,indices=nbrs.kneighbors(x)
distances=np.sort(distances,axis=0)
distances=distances[:,2]
plt.plot(distances)

db=DBSCAN(eps=2.5,min_samples=5)
db.fit(x)

db.fit_predict(x)
c=pd.DataFrame(db.labels_,columns=['cluster'])
pd.concat([df,c],axis=1)

from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca_values_dbscan = pca.fit_transform(x)

plt.figure(figsize=(7,7))
sns.scatterplot(x=pca_values_dbscan[:,0], y=pca_values_dbscan[:,1], hue=db.labels_, palette='Set1', s=60)
plt.title('DBSCAN Clustering Visualization (PCA)')
plt.show()

best_score2=silhouette_score(x,db.labels_)
best_score2

from scipy.cluster.hierarchy import linkage, dendrogram
import matplotlib.pyplot as plt
# Generate the linkage matrix
linked = linkage(df, method='ward') # 'ward' minimizes the variance within each cluster

# Plot the dendrogram
plt.figure(figsize=(15, 7))
dendrogram(linked,p=6,
           truncate_mode='level',
           orientation='top',
           distance_sort='descending',
           show_leaf_counts=True)
plt.title('Hierarchical Clustering Dendrogram')
plt.xlabel('Data Points')
plt.ylabel('Euclidean Distances')
plt.show()

from sklearn.cluster import AgglomerativeClustering

# Apply Agglomerative Clustering
hierarchical_model = AgglomerativeClustering(n_clusters=3, metric='euclidean', linkage='ward')
hierarchical_labels = hierarchical_model.fit_predict(df)

# Add the hierarchical cluster labels to the DataFrame
df['Hierarchical_Cluster'] = hierarchical_labels

print('Hierarchical Cluster counts:')
print(df['Hierarchical_Cluster'].value_counts())

from sklearn.decomposition import PCA
import seaborn as sns
import matplotlib.pyplot as plt

# Re-run PCA to get the components for visualization if not already done with the full dataset
pca = PCA(n_components=2)
pca_values = pca.fit_transform(df)

# Visualize the hierarchical clusters using PCA
plt.figure(figsize=(10, 7))
sns.scatterplot(x=pca_values[:, 0], y=pca_values[:, 1], hue=df['Hierarchical_Cluster'], palette='Set1', s=60)
plt.title('Hierarchical Clustering Visualization (PCA)')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.show()



from sklearn.metrics import silhouette_score

best_score3 = silhouette_score(df, hierarchical_labels)
print(f"The Silhouette Score for Agglomerative Clustering is: {best_score3}")



from sklearn.mixture import GaussianMixture
from sklearn.decomposition import PCA
import seaborn as sns
import matplotlib.pyplot as plt

# Initialize and fit the Gaussian Mixture Model with 3 components
gmm = GaussianMixture(n_components=3, random_state=42, n_init=10)
gmm_labels = gmm.fit_predict(df)

# Add the GMM cluster labels to the DataFrame
df['GMM_Cluster'] = gmm_labels

print('GMM Cluster counts:')
print(df['GMM_Cluster'].value_counts())

# Re-run PCA to get the components for visualization if not already done with the full dataset
pca = PCA(n_components=2)
pca_values = pca.fit_transform(df)

# Visualize the GMM clusters using PCA
plt.figure(figsize=(10, 7))
sns.scatterplot(x=pca_values[:, 0], y=pca_values[:, 1], hue=df['GMM_Cluster'], palette='Set1', s=60)
plt.title('Gaussian Mixture Model Clustering Visualization (PCA)')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.show()

from sklearn.metrics import silhouette_score

best_score4 = silhouette_score(features, gmm_labels)
print(f"The Silhouette Score for Gaussian Mixture Model is: {best_score4}")

from sklearn.cluster import Birch

# Initialize Birch model with n_clusters=3
birch = Birch(n_clusters=3)

# Fit the Birch model to the features DataFrame and predict cluster labels
birch_labels = birch.fit_predict(df)

# Add the generated cluster labels as a new column 'Birch_Cluster' to the proj DataFrame
df['Birch_Cluster'] = birch_labels

print('Birch Cluster counts:')
print(df['Birch_Cluster'].value_counts())

plt.figure(figsize=(10, 7))
sns.scatterplot(x=pca_values[:, 0], y=pca_values[:, 1], hue=df['Birch_Cluster'], palette='Set3', s=60)
plt.title('Birch Cluster Model Clustering Visualization (PCA)')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.show()

from sklearn.metrics import silhouette_score

best_score5 = silhouette_score(features, birch_labels)
print(f"The Silhouette Score for Birch Label Model is: {best_score5}")

import matplotlib.pyplot as plt
#here plotting silhouette scores for each model to choose best fitted clustering
# Create a list of silhouette scores
silhouette_scores = [
    best_score1, # KMeans
    best_score2, # DBSCAN
    best_score3, # Agglomerative Clustering
    best_score4, # Gaussian Mixture Model
    best_score5  # Birch Clustering
]

# Create a list of corresponding labels
clustering_methods = [
    'K-Means',
    'DBSCAN',
    'Agglomerative',
    'Gaussian Mixture',
    'Birch'
]

# Create the bar plot
plt.figure(figsize=(10, 6))
plt.bar(clustering_methods, silhouette_scores,color='orange')
plt.xlabel('Clustering Method')
plt.ylabel('Silhouette Score')
plt.title('Comparison of Silhouette Scores for Different Clustering Methods')
plt.show()

df

df=pd.concat((df,target),axis=1)
df.head()

!pip install joblib

import joblib
import pickle
'''
df['Birch_Cluster']=birch_labels
df['GMM_Cluster'] = gmm_labels
df['hierarchical_labels'] = hierarchical_labels
df['KMeans_Cluster'] = cluster_labels

'''
df.to_csv('multi_cluster_data.csv', index=False)
joblib.dump(hierarchical_model, "hierarchial_model.pkl")
joblib.dump(kmeans, "kmeans.pkl")
joblib.dump(gmm, "gmm.pkl")
joblib.dump(birch, "birch.pkl")

print("Models saved successfully")

!pip install -q streamlit

import streamlit as st
import pickle
import warnings
warnings.filterwarnings('ignore')

'''
pickle.dump(kmeans,open('kmeans.pkl','wb'))
pickle.dump(hierarchical_model,open('hierarchial_model.pkl','wb'))
pickle.dump(gmm,open('gmm.pkl','wb'))
pickle.dump(birch,open('birch.pkl','wb'))
'''

#!npm install -g localtunnel -U

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Model_Dep_app.py
# import streamlit as st
# import pickle
# import pandas as pd
# import numpy as np
# import joblib
# df=pd.read_csv('multi_cluster_data.csv')
# @st.cache_resource
# def load_models():
#     kmeans = joblib.load("kmeans.pkl")
#     gmm = joblib.load("gmm.pkl")
#     hierarchical = joblib.load("hierarchial_model.pkl")
#     birch = joblib.load("birch.pkl")
#     return kmeans, gmm, hierarchical, birch
# kmeans, gmm, hierarchical, birch = load_models()
# 
# # --------------------------------------------------
# # Sidebar Selections
# # --------------------------------------------------
# method = st.sidebar.selectbox(
#     "Select Clustering Method",
#     ("KMEANS", "GMM", "BIRCH", "HIERARCHICAL")
# )
# 
# country = st.sidebar.selectbox(
#     "Select Country",
#     df["Country"].unique()
# )
# status_map = {
#     0: "🔴 Least Developed",
#     1: "🟡 Developing",
#     2: "🟢 Highly Developed"
# }
# 
# country_data = df[df["Country"] == country]
# X = country_data.drop(columns=["Country"])
# if st.button("Predict Cluster"):
# 
#     if method == "KMEANS":
#         cluster = kmeans.predict(X)[0]
# 
#     elif method == "GMM":
#         cluster = gmm.predict(X)[0]
# 
#     elif method == "BIRCH":
#         cluster = birch.predict(X)[0]
# 
#     elif method == "HIERARCHICAL":
#         cluster = hierarchical.predict(X)[0]
# 
#     st.subheader(f"📍 {country} belongs to:")
# 
#     st.success(f"{status_map.get(cluster, 'Unknown')} (Cluster {cluster})")
# 
#

import urllib
print("Password for localtunnel is:", urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip())

!streamlit run Model_Dep_app.py & npx localtunnel --port 8501







"""# Task
Correct the spelling of `hierarchial_labels` to `hierarchical_labels` and `cluster_label` to `cluster_labels` in cell `ER4NHHnPBpvZ` to match how the variables were previously defined.

## Correct variable names in cell ER4NHHnPBpvZ

### Subtask:
Correct the spelling of `hierarchial_labels` to `hierarchical_labels` and `cluster_label` to `cluster_labels` in cell `ER4NHHnPBpvZ` to match how the variables were previously defined.

## Summary:

No solving process was provided, so there are no findings or insights to summarize.
"""